org: elderpattenferreira
app: memebase
# serverless.yml

service: serverless-flask

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: falsepyproject.toml
  pythonRequirements:
    dockerizePip: non-linux
    usePipenv: false

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-2
  apiGateway:
    shouldStartNameWithService: true

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

package:
  exclude:
    - node_modules/**
    - web/**
    - .git/**